### ISSUE TITLE
unexpected results

### ISSUE THREAD

**Issue by askasjoe** [XingruiWang/Animefy#1]
i ran `sh latent.sh` and `python generate.py` for the pic below
![image-20220310180008767](https://user-images.githubusercontent.com/35868485/157638346-e9e72a14-66f1-41ce-8227-1b94c9068664.png)
but only get the results
![unknown](https://user-images.githubusercontent.com/35868485/157638522-0cc976ec-1ca7-4136-9ddf-30a95ae7f0e8.png)
any suggestions? thanks~

**Comment by askasjoe** [comment]
i also tried different models you provided(`G_out.pth`, `G_blend.pth`) and diffrent steps(e.g. 200, 1000, 5000) but the results were similar

**Comment by XingruiWang** [comment]
Hi, thanks for your interest.

I think you can try on the google colab for another time, to make sure we have the same way of projection.

I tried just now and got the following result:

![image](https://user-images.githubusercontent.com/36118382/183260322-b7620a96-7e9b-4a72-af10-d5ce1c36078f.png)

In fact, using layer swapping is an interesting way to generate image affect, but it's not robust. But it should render a plausible cartoon image. I think you can tried again.

Plus, more iterations on projection can achieve a lower loss, but I found it will cause over fitting and won't brings better effect on the final result. Hopefully, the model should have generation fancy cartoon image with any latent code, so some of the reasons I think should be:

1. The model is still under fitted, even though I have trained for many days with multiple GPUs. 
2. The StyleGAN method do not have the detection of facial features, all of the transformation rely on the optimal transporting way from the original face image domain to the cartoon image domain. But in the cartoon image I used, the eyes are quite big and noses are quite small, which sometime will confuse the model, compared with the real human faces. And indeed, when I train the model, I found sometimes the nose will be transformed to mouth from the original face to cartoon face.
